name: example-file-upload

on:
  pull_request:
    types:
      - opened

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: microsoft/powershell@v1

      - name: Install SharePointPnPPowerShellOnline module
        run: |
          Install-Module -Name SharePointPnPPowerShellOnline -Force -AllowClobber

      - name: Upload file to GitHub Actions
        run: |
          cp C:/Users/nxy/Documents/Documents_NXY/Folder-test/aaaa.txt $GITHUB_WORKSPACE/aaaa.txt

      - name: Upload file to SharePoint
        run: |
          $clientID = ${{ secrets.CLIENT_ID }}
          $clientSecret = ${{ secrets.CLIENT_SECRET }}
          $tenantID = ${{ secrets.TENANT_ID }}
          $siteID = "Test_GitHubActions"
          $filePath = "Shared Documents/Test_Upload_File/Evd"

          $secpasswd = ConvertTo-SecureString $clientSecret -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ($clientID, $secpasswd)

          Connect-PnPOnline -ClientId $clientID -ClientSecret $clientSecret -Tenant $tenantID
          Add-PnPTenantAppCatalogSite -Site $siteID
          Add-PnPFile -Path $filePath -Folder "Shared Documents" -Connection $cred
        # run: |
        #   pwsh -File ./.github/scripts/execute-data-patch.ps1
