name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Thêm các bước khác để chạy datapatch và tạo file ở đây

      - name: Create Excel file
        run: |
          # Thực hiện tạo tệp Excel ở đây
          touch example.xlsx

      - name: Move file to SharePoint in Microsoft Teams
        env:
          SHAREPOINT_URL: https://cmcglobalcompany.sharepoint.com/:f:/r/sites/Test_GitHubActions/Shared%20Documents/Test_Upload_File
          SHAREPOINT_FOLDER: Evd
        run: |
          # Di chuyển tệp đến SharePoint
          curl -X PUT -T example.xlsx "https://cmcglobalcompany.sharepoint.com/:f:/r/sites/Test_GitHubActions/Shared%20Documents/Test_Upload_File/Evd/example.xlsx"
      - name: Log SHAREPOINT_URL--------------------
        run: |
          # Xem URL
          echo "SHAREPOINT_URL_FULL: $SHAREPOINT_URL/$SHAREPOINT_FOLDER/example.xlsx"
