name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Excel file
        run: |
          # Thực hiện tạo tệp Excel ở đây
          touch example.xlsx
      - name: Move file to SharePoint in Microsoft Teams1
        uses: KoenZomers/SharePoint-UploadFile@master
        with:
          siteUrl: 'https://cmcglobalcompany.sharepoint.com/sites/Test_GitHubActions'
          documentLibrary: 'Shared%20Documents/Test_Upload_File/Evd'
          sourceFolder: './'
          fileToUpload: 'example.xlsx'
