name: example-file-upload
on:
  pull_request:
    types:
      - opened
jobs:
  get_report:
    runs-on: ubuntu-latest
    steps:
      - name: Create Test File
        run: touch /tmp/foo.txt
      - name: Send to Sharepoint
        uses: Y97qb/sharepoint-file-upload-action@1.0.0
        with:
          file_path: "*.txt"
          host_name: 'cmcglobalcompany.sharepoint.com'
          site_name: 'Test_GitHubActions'
          upload_path: 'Test_Upload_File/Evd'
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          client_secret: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}