name: example-file-upload

on:
  push:
    branches:
      - feature/nxy-45

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file
        run: |
          echo "This is a sample file." > $GITHUB_WORKSPACE/aaaa.txt

      - name: Upload File to SharePoint
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
          CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
        run: |
          pwsh -File ./.github/scripts/execute-data-patch.ps1
