name: example-file-upload

on:
  push:
    branches:
      - feature/nxy-45

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call File execute-data-patch.ps1
        shell: pwsh
        run: |
          pwsh -File ./.github/scripts/execute-data-patch.ps1
